### ISSUE TITLE
Add new multi-page documents to Facebook Data Processing Agreement

### ISSUE THREAD

**Issue by afisher3578** [OpenTermsArchive/pga-declarations#141]
Service: Facebook
Declaration: Data Processing Agreement

URL: https://www.facebook.com/legal/Workplace_GDPR_Addendum
URL: https://www.facebook.com/legal/terms/dataprocessing

**Comment by smmkolesnikov** [comment]
Solved here
https://github.com/OpenTermsArchive/pga-declarations/pull/247
