### ISSUE TITLE
Cannot read properties of `undefined` (reading 'service')

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/pga-declarations#157]
Since #155, the following error is raised on every run:

```
unhandledRejection: Cannot read properties of undefined (reading 'service')
TypeError: Cannot read properties of undefined (reading 'service')
at Function.formatIssueTitleAndBody (…/pga/node_modules/@opentermsarchive/engine/src/tracker/index.js:183:41)
at Tracker.onInaccessibleContent (…/pga/node_modules/@opentermsarchive/engine/src/tracker/index.js:73:37)
at Archivist.emit (node:events:525:35)
```

The failing module is the one that updates issues on GitHub. This does not seem to block runs since [snapshots are still updated](https://github.com/OpenTermsArchive/pga-snapshots/tree/main). However, I see no new version since then, so it could be that versions are not properly extracted anymore (it could also just be coincidence). 

I had never seen that error before. The faulting line (`src/tracker/index.js:183`) has not been changed in the last three months. I see no related breaking changes in the [Changelog](https://github.com/OpenTermsArchive/engine/blob/02ae930c52122d8a893cb9fdf4288e6b4bfc0bb2/CHANGELOG.md).

It seems that one instance of `terms` cannot be destructured because it does not contain the `service` property.
I checked and every service declared in PGA has a `name`.

Since this issue is seen only in PGA, I file it first in this collection, but I suspect the problem is more related to the engine and I will open an issue in the engine too.

**Comment by afisher3578** [comment]
Thank you for opening this issue, I have never seen this before either. I see that the latest versions was updated 2 weeks ago. Let us know if there is anything we need to do on our end.

**Comment by MattiSG** [comment]
Fixed by https://github.com/OpenTermsArchive/engine/pull/1013 via https://github.com/OpenTermsArchive/pga-declarations/pull/161
