### ISSUE TITLE
Fix Quora - Community Guidelines 

### ISSUE THREAD

**Issue by pg-adrian** [OpenTermsArchive/pga-declarations#172]
Quora Community Guidelines versions have  a section on top "Acceptable Use Policy" that is not part of the current CG page:
https://help.quora.com/hc/en-us/articles/360000470706-Platform-Policies

I think there is something wrong with the links but didn't get it completely after checking the snapshots

**Comment by smmkolesnikov** [comment]
Hi @pg-adrian! Fixed it here https://github.com/OpenTermsArchive/pga-declarations/pull/182
