### ISSUE TITLE
Fix Tiktok - Trackers Policy 

### ISSUE THREAD

**Issue by pg-adrian** [OpenTermsArchive/pga-declarations#185]
See problem with https://github.com/OpenTermsArchive/pga-versions/commit/71bc0c7a7d6e57f92c1c04416ae6309b2a596ce7 

Please change URL to https://www.tiktok.com/legal/page/global/tiktok-website-cookies-policy/en

**Comment by smmkolesnikov** [comment]
Hi @pg-adrian! Currently I cannot update this policy as there is an issue with a checkup (see [here](https://github.com/OpenTermsArchive/pga-declarations/pull/191#issuecomment-1817911691)). Hopefully we can find a way to fix it with the OTA team

**Comment by smmkolesnikov** [comment]
See discussion here: https://github.com/OpenTermsArchive/pga-declarations/pull/246

**Comment by smmkolesnikov** [comment]
Finally solved here
https://github.com/OpenTermsArchive/pga-declarations/pull/250
