### ISSUE TITLE
Examine Facebook Trackers Policy 

### ISSUE THREAD

**Issue by pg-adrian** [OpenTermsArchive/pga-declarations#189]
Please check this version because it looks like it registered a version with no change: 

https://github.com/OpenTermsArchive/pga-versions/commit/bf623d58a8e2fdf923f9ce0a0f3c3023e8fa6e2c

**Comment by smmkolesnikov** [comment]
Hi @pg-adrian! As far as I can see there are no substantial changes here. Shall we close the issue then?

**Comment by pg-adrian** [comment]
Hi @smmkolesnikov, ok thank you! I was just curious why it came up as a new version then but if it just happens once and isn't a regular thing, then I guess we can discard it?
