### ISSUE TITLE
Fix Quora - Privacy Policy 

### ISSUE THREAD

**Issue by pg-adrian** [OpenTermsArchive/pga-declarations#197]
Please leave out this part at the bottom: 

[Prior versions](https://www.quora.com/about/privacy_archive)

[Contact us](https://www.quora.com/contact)

[Press](https://www.quora.com/press)

[Terms of service](https://www.quora.com/about/tos)

[Privacy Policy](https://www.quora.com/about/privacy)

[Acceptable Use](https://www.quora.com/about/acceptable_use)

**Comment by smmkolesnikov** [comment]
Hello @pg-adrian! Fixed here https://github.com/OpenTermsArchive/pga-declarations/pull/219
