### ISSUE TITLE
Create new declaration - Facebook Data Processing Terms 

### ISSUE THREAD

**Issue by pg-adrian** [OpenTermsArchive/pga-declarations#267]
Please create a new declaration for FB with the terms type "User Consent Policy" as a multi-page document which includes these links: 

Mainpage: https://www.facebook.com/legal/terms/dataprocessing 
Subpage 1: https://www.facebook.com/legal/EU_data_transfer_addendum/update
Subpage 2: https://www.facebook.com/legal/terms/UK_Data_Transfer_Addendum

**Comment by smmkolesnikov** [comment]
Done here: https://github.com/OpenTermsArchive/pga-declarations/pull/305
