### ISSUE TITLE
Create new declaration - Instagram Trackers Policy 

### ISSUE THREAD

**Issue by pg-adrian** [OpenTermsArchive/pga-declarations#270]
Please create new declaration for Instagram with the terms type "Trackers Policy" with this URL: https://privacycenter.instagram.com/policies/cookies/

**Comment by smmkolesnikov** [comment]
<img width="756" alt="Screenshot 2024-04-17 at 10 09 24" src="https://github.com/OpenTermsArchive/pga-declarations/assets/86059054/0b178b62-93db-428c-a881-f243fe0e1c2c">
The engine cannot reach this page for some reason. Also in the browser it is only displayed in German, you can only switch to English when using VPN.

**Comment by smmkolesnikov** [comment]
Fixed here: https://github.com/OpenTermsArchive/pga-declarations/commit/771c12101fdb204a3bdeed04667889f68ce1eee6
