### ISSUE TITLE
Fix Declaration - Quora Community Guidelines 

### ISSUE THREAD

**Issue by pg-adrian** [OpenTermsArchive/pga-declarations#272]
Please add the following links as further subpages to the Quora Community Guidelines declaration: 

https://help.quora.com/hc/en-us/articles/9456583756180-Questions-and-Answers-Policies
https://help.quora.com/hc/en-us/articles/360000470306-What-is-Quora-s-policy-on-adding-images-and-videos
https://help.quora.com/hc/en-us/articles/360057638052-What-is-Quora-s-policy-on-credentials
https://help.quora.com/hc/en-us/articles/360015467632-What-is-Quora-s-policy-for-posting-reviews-of-businesses-products-or-services
https://help.quora.com/hc/en-us/articles/360055133711-What-is-Quora-s-policy-on-disclosing-affiliations-in-answers
https://help.quora.com/hc/en-us/articles/360000470206-What-is-Quora-s-policy-on-plagiarism-and-attribution
https://help.quora.com/hc/en-us/articles/4405052142868-What-is-considered-Adult-content-on-Quora
https://help.quora.com/hc/en-us/articles/360052494012-How-does-Quora-intend-to-enforce-the-Not-for-Reproduction-feature

**Comment by smmkolesnikov** [comment]
The engine cannot fetch these terms on GitHub, see the problem here: https://github.com/OpenTermsArchive/pga-declarations/pull/298
