### ISSUE TITLE
Fix Declaration - Reddit Community Guidelines

### ISSUE THREAD

**Issue by pg-adrian** [OpenTermsArchive/pga-declarations#273]
Here we have just a small issue but the titles of the different subpage URLs are not included in the document for for instance, the text of the first URL (https://support.reddithelp.com/hc/en-us/articles/360043071072-Do-not-threaten-harass-or-bully) is fetched without the headline (Do not threaten, harass, or bully). If possible included the headlines in the selection would make it easier to read the final document

**Comment by smmkolesnikov** [comment]
For some reason the engine cannot reach Reddit Community Guidelines when I work from my local device (403 error), even though they are available in the browser

**Comment by smmkolesnikov** [comment]
Closing this issue for now as there technical problems with tracking Reddit CG
