### ISSUE TITLE
Fix declaration - Twitch Community Guidelines 

### ISSUE THREAD

**Issue by pg-adrian** [OpenTermsArchive/pga-declarations#279]
Please include the following subpages/URLs in the declaration for the Twitch Community Guidelines: 

https://help.twitch.tv/s/article/about-account-suspensions-dmca-suspensions-and-chat-bans?language=en_US 
https://safety.twitch.tv/s/article/Prohibited-Games?language=en_US
https://safety.twitch.tv/s/article/Content-Classification-Guidelines?language=en_US
https://safety.twitch.tv/s/article/Emote-Policy?language=en_US
https://safety.twitch.tv/s/article/Tags-Guidelines?language=en_US
https://safety.twitch.tv/s/article/Usernames?language=en_US

**Comment by smmkolesnikov** [comment]
Done here: https://github.com/OpenTermsArchive/pga-declarations/pull/294
