### ISSUE TITLE
Fix declaration - X Community Guidelines 

### ISSUE THREAD

**Issue by pg-adrian** [OpenTermsArchive/pga-declarations#283]
Please at the following links for subpages to the X Community Guidelines declaration: 

https://help.twitter.com/en/rules-and-policies/x-username-squatting
https://help.twitter.com/en/rules-and-policies/copypasta-duplicate-content
https://help.twitter.com/en/rules-and-policies/financial-scam
https://help.twitter.com/en/rules-and-policies/financial-scam
https://help.twitter.com/en/rules-and-policies/abusive-profile
https://help.twitter.com/en/rules-and-policies/automated-claims-policy
https://help.twitter.com/en/rules-and-policies/counterfeit-goods-policy
https://help.twitter.com/en/rules-and-policies/public-interest
https://help.twitter.com/en/rules-and-policies/x-limits
https://help.twitter.com/en/rules-and-policies/x-reach-limited
https://help.twitter.com/en/rules-and-policies/enforcement-options
https://help.twitter.com/en/rules-and-policies/x-moments-guidelines-and-principles
https://help.twitter.com/en/rules-and-policies/fair-use-policy

**Comment by smmkolesnikov** [comment]
Done here: https://github.com/OpenTermsArchive/pga-declarations/pull/299
